### ISSUE TITLE
Error: Cannot find module 'request'

### ISSUE THREAD

**Issue by peterschussheim** [lucaperret/vscode-now#1]
Hi, just tried out your extension but it fails to work.  Any command I try to use from this ext returns an error notification in the bottom right of the editor.  Dev tools console shows multiple error logs related to `Error: Cannot find module 'request'`.

## Screenshot

<img width="1614" alt="now-extension-error" src="https://user-images.githubusercontent.com/3654683/39158338-7b5cbbb8-472d-11e8-9ae1-4dbc8c1a2efa.png">

**Comment by lucaperret** [comment]
Hi @peterschussheim, have you tried to reinstall the extension ?

**Comment by peterschussheim** [comment]
Yes, I tried twice last night to reinstall.

**Comment by lucaperret** [comment]
It was missing the peer dependency of `request-promise-native`. Could you retry ?

**Comment by peterschussheim** [comment]
Hi Luca,

Thank you, it works now!  This is a very nice extension, I look forward to using it and contributing if needed. 😃 

Peter
